### ISSUE TITLE
How to make multiple requests?

### ISSUE THREAD

**Issue by emcniece** [tjfontaine/node-dns#105]
Currently trying to make a DNS lookup tool that accepts an array of domain names. What is the best way to process a batch of questions? Should requests be deferred, or promise chained?

Implementation: https://github.com/emcniece/dns-lookup/blob/master/src/server/routes.js#L44

**Comment by finom** [comment]
Use ``'ANY'`` resource type. But keep in mind you may get records non [handled by the library](https://github.com/tjfontaine/node-dns#resourcerecord).

**Comment by WoZ** [comment]
@emcniece 

Hello! I've found that this module is unsupported and has some bugs. I may propose to use our module that was tested in production and highload environments. Also we have good unit and functional tests [with 100% coverage](https://coveralls.io/github/LCMApps/dns-lookup-cache?branch=master), multi-records resolving and TTL support. Here it is: https://github.com/LCMApps/dns-lookup-cache
