### ISSUE TITLE
Broken! "dgram" module does not exist anymore!

### ISSUE THREAD

**Issue by cyberbizness** [tjfontaine/node-dns#117]
I'm having this problem when trying to install the fork https://github.com/tutosfaciles48/node-dns. As strange as it could be... The package dgram is not available anymore. 

MAKE A BACKUP BEFORE! ;-)
When you install it whith NPM you will get an empty folder with this message : 

# Security holding package

This package name is not currently in use, but was formerly occupied
by another package. To avoid malicious use, npm is hanging on to the
package name, but loosely, and we'll probably give it to you if you
want it.

Is there a stable version somewhere of that package ?

**Comment by cyberbizness** [comment]
Because the issue section of this repo is close and the readme says : "If it doesn't please file an issue." with a link here... The only other solution was to not filling any issue and not share anything with the community.

**Comment by taoeffect** [comment]
> "If it doesn't please file an issue." with a link pointing here..

They just copy/pasted that text from this repo. Closing since this apparently is an issue with a different fork. Contact the maintainer of the fork (@tutosfaciles48) and ask them to open issues.
