### ISSUE TITLE
Proxying requests?

### ISSUE THREAD

**Issue by daguej** [tjfontaine/node-dns#2]
What's the best way to proxy DNS requests?  For example, in [ndns](https://github.com/atrniv/ndns) it is simple:

```
server.on("request", function(req, res) {
    var c_req = client.request(REMOTE_PORT, REMOTE_HOST);
    c_req.on("response", function (c_res) {
        res.send(c_res);
    });
    c_req.send(req);
});
```

**Comment by vohof** [comment]
Hi, can you provide an example on how "proxy" the requests to Google's DNS?
