### ISSUE TITLE
Error on server start due to the binaryheap package

### ISSUE THREAD

**Issue by brnrd** [tjfontaine/node-dns#51]
I need to do a custom resolve, so I do the following code in a class : 
    
    dns = require 'native-dns'
    (...)

         @resolve = (url, server, ip) ->
			question = dns.Question({
				name: url,
				type: 'A'})
			start = Data.now()
			req = dns.Request({
				question: question,
				server: {address: server}
				})
			req.on('timeout', () ->
				console.log 'Timeout')
			req.on('message', (err, answer) ->
				console.log answer
				answer.answer.forEach(a) ->
					console.log a.address
			)
			req.on('end', () ->
				delta = Date.now() - start
				console.log 'Finished processing request: ' + delta.toString() + 'ms'
			)
			req.send()

But on start, the server raise this error : 

    /node_modules/native-dns/node_modules/binaryheap/binaryheap.js:68
    if (!insert._left)
               ^
    TypeError: Cannot read property '_left' of null
    at [object Object].Heap.insert

I've seen the issue #33 but the .platform.cache = false but it doesn't change anything to the problem.

Am I doing something wrong or does the Binaryheap package needs a fix ?

Thanks !

**Update :** I only get this problem under Ubuntu 13.04. It works fine under Windows 7.
**Update 2 :** I also get this problem with my app on Heroku. As working under Windows 7 is not that much of a problem, Heroku is a bigger problem.
**Update 3 :** The problem happens also with AppFog and Nodejitsu. I really hope you can fix this problem.

**Comment by fralec** [comment]
I have this issue with Ubuntu 16.10 :'(
