### ISSUE TITLE
DNS Server performance issue

### ISSUE THREAD

**Issue by asyncer** [tjfontaine/node-dns#99]
I've used the simple example of node-dns module, but it respond to request in more than 1 second usually, while my bind respond in 10 millisecond,
Is this slow performance normal? I'm disappointed with this performance test.

**Comment by asyncer** [comment]
That was my mistake to lookup the DNS server via localhost address, this had added an OS interrupt to lookup in hosts file.
making test via 127.0.0.1 was done in less than 100 milliseconds,

Thanks

**Comment by coolaj86** [comment]
close the issue?
